package com.example.diagnosisapp;

import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.Intent;
import android.database.Cursor;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.inputmethod.EditorInfo;
import android.widget.SearchView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

public class  MainActivity extends AppCompatActivity {

    static List<String> list2;
    static List<String> list3;
    static List<String> list4;
    static List<String> list5;

    private RecyclerView mRecyclerView;
  static   DBHelper dbHelper;
    private adapterClass adapter;
    private List<symptomsClass> exampleList;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        dbHelper = new DBHelper(MainActivity.this);
        list2 = new ArrayList<>();
        list3 = new ArrayList<>();
        list4 = new ArrayList<>();
        list5 = new ArrayList<>();

        fillExampleList();
        setUpRecyclerView();
       storeDataInArrays();   //Read the data from database

    }

    void storeDataInArrays() {
        Cursor cursor = dbHelper.readAllData();
        if (cursor.getCount() == 0) {
            Toast.makeText(this, "No Data", Toast.LENGTH_SHORT).show();
        }
        else
            {
            while (cursor.moveToNext()) {
               list2.add(cursor.getString(0));
                list3.add(cursor.getString(1));
                list4.add(cursor.getString(2));
                list5.add(cursor.getString(3));
            }
        }


    }
    private void fillExampleList() {
        exampleList = new ArrayList<>();

        exampleList.add(new symptomsClass( "Allergy", "Allergy is a very individualor to-each-his-own medical condition. Put simply, what your body may be allergic to, the other person may not be and the other way round. Allergy is a sudden hypersensitive reaction that presents itself with a number of symptoms following contact with an allergen. Now, what is an allergen? It’s an agent that is harmful to a sensitive or allergic person but does not have any effect on others. The main allergens are dust mites, pollens, animal danders and certain food items like eggs. The main allergies are nasal allergy, allergic cough, food allergies, dust allergy and skin rash. Some persons are very allergic to hair dyesas well. The Homeopathic remedies for allergy not only helps in providing relief in acute attacks of allergy, but also works to cure the allergy by extracting the underlying root cause. The Homeopathic treatment for allergy is completely safe, since the homeopathic medicines are sourced out of natural substances and there are no toxins involved. The natural Homeopathic remedies that are best suited are chosen on the basis of the symptoms and characteristics narrated by each patient.","Apis Mellifica\t•Arsenic Album\t•Natrum Mur\t Sulphur","https://www.drhomeo.com/allergy/top-homeopathic-remedies-for-allergy/"));
        exampleList.add(new symptomsClass( "Dust allergy", "Dust allergy is an immediate allergic response caused by exposure to dust and dust mites. Dust mites are tiny microorganisms found mostly in bed linen, mattresses, and furniture. Dust allergy usually occurs in people who live in warm, humid and damp places. Symptoms of dust allergy range from mild to severe. The main symptoms of dust allergy are sneezing, a runny nose, and itching of the eyes and nose. The patient may also have difficulty in breathing, a cough, and itching on the roof of the mouth. Dust allergy which persists for a long time may result in chronic cases of asthma. Homeopathic treatment for dust allergy is a permanent, rapid and safe cure. It is made of natural substances which are not toxic and do not have any side effects. They are not habit forming and can be safely taken for extended periods of time. This treatment works to stimulate the weakened immune system. The benefit of using homeopathy is that it stops the recurrent episodes of disease. Homeopathy is effective in all age groups.  ","Allium Cepa\t•Arsenic Album\t•Arundo\t•Sabadilla","https://www.drhomeo.com/homeopathic-treatment/homeopathic-treatment-dust-allergy/"));
        exampleList.add(new symptomsClass("Peanut Allergy","A food item as simple as a peanut can trigger an allergy in some people. Allergy basically refers to an abnormal exaggerated immune response to a substance (or allergen) in an individual who is allergic towards the specific allergen. When the allergic reaction is life-threatening, it is referred to as Anaphylaxis. Peanut intake leading to such an allergic response is termed Peanut Allergy. Here the allergen is peanut and the person in whom eating a peanut excites a reaction is allergic towards peanuts. The Homeopathic remedies for peanut allergy are of great help in the treatment of Allergy and work towards extracting the allergy from its root. These natural remedies strengthen the immune system and the severity of an allergic reaction is reduced.","•Apis Mellifica \\t•Rhus Tox\\t•Nux Vomica\\t•Astacus Fluviatilis\\t•Natrum Mur\\t•Pulsatilla\\t• Astacus Fluviatilis","https://www.drhomeo.com/allergy/homeopathic-remedies-for-peanut-allergy/"));
        exampleList.add(new symptomsClass("Milk allergy","Milk allergy is a common food allergy among children. It results from an over-reaction of the immune system towards the protein in the milk or milk products. In children who are allergic to milk, the immune system recognizes the protein in the milk as a harmful foreign substance and starts an immune reaction to fight against it. This symptoms related to this immune reaction varies from person to person. Homeopathic medicines treat milk allergy by optimizing the immune system. Once the immune system is moderated, the intensity and severity of the symptoms get reduced.","•Natrum Carb\\t•Magnesia Muriatica\\t• Apis Mellifica\\t•Calcarea Carb\\t•Aethusa Cynapium\\t•Pulsatilla Nigricans","https://www.drhomeo.com/homeopathic-treatment/milk-allergy-homeopathy/"));
        exampleList.add(new symptomsClass("Pollen Allergy","The sudden appearance of symptoms like sneezing, runny nose, and watery eyes as a result of inhaling pollens is known as a pollen allergy. An inflammatory response against the pollen grains is triggered by the immune system of a person allergic to pollen. Of the many substances that can cause a seasonal allergy, pollens remain one of the most common triggers. Pollen is a powdery substance produced by flowers, weeds, trees, and grass. Most trees produce pollen during the spring season; flowers and grasses produce pollen during the summertime, and late-blooming plants like ragweed produce pollen around late summer and early autumn. Homeopathic medicine for allergy caused by pollen grains can treat acute allergic reactions, as well as chronic allergic tendencies.","•Natrum Mur\t•Sabadilla Officinalis\t•Arsenic Album\t•Allium Cepa\t•Euphrasia Officinalis\t•Arsenic Iod \t•Arum Triphyllum","https://www.drhomeo.com/allergy/pollen-allergy-homeopathy/"));
        exampleList.add(new symptomsClass("Eye Allergy","Homeopathy offers excellent help in cases of an eye allergy. Initially, it helps in treating acute symptoms of eye allergies. Following this, it aims to address the chronic tendency of eye allergies. The medicines used in the homeopathic system for managing eye allergies are of natural origin and treat allergies without any side effects.","•Euphrasia Officinalis\\t•Natrum Mur\\t•Ambrosia Artemisiifolia\\t•Allium Cepa\\t•Apis Mellifica\\t•Pulsatilla Nigricans","https://www.drhomeo.com/homeopathic-treatment/homeopathic-medicine-for-eye-allergies/"));
        exampleList.add(new symptomsClass("Ankle Pain","Ankle pain not only hampers movement, but the niggling pain also affects a person’s general frame of mind. Ankle is a joint between the leg and foot. The bones that participate in forming the ankle joint are tibia and fibula (both are bones of leg), plus talus bone (bone of foot).","•Arnica\t•Ruta Graveolens\t•Rhus Tox\t•Ledum Pal\t•Carbo Animalis\t•Bryonia","https://www.drhomeo.com/joint/homeopathic-remedies-for-ankle-pain/"));
        exampleList.add(new symptomsClass("Anosmia","Anosmia is a condition in which a person loses their sense of smell. Smell is one of the five senses a human being possesses. The odor molecules in the air surrounding us enter our nostrils, and are detected by the olfactory receptors. These receptors send a signal to the brain center via a nerve where the smell is identified. This is how we identify different smells and odors. Anosmia may arise due to swelling in the nose, blockage in the nose or due to damage to brain/olfactory nerve/olfactory receptors.","•Silicea\t•Kali Bichromicum \t•Natrum Mur\t•Lemna Minor","drhomeo.com/homeopathic-treatment/anosmia-natural-homeopathic-medicines-loss-of-smell/"));
        exampleList.add(new symptomsClass("Anxiety","Anxiety refers to a mental state of nervousness, fear, and worry. Getting anxious once in a while on certain occasions is a regular part of life. For example getting anxious before an examination, while giving an interview or during stressful events is somewhat normal. The anxiety on such occasions is short-lived and temporary. But anxiety becomes a problem when the reaction of the person in a given situation appears in a highly intense form and out of proportion than what one usually expects. If the episodes of such extreme anxiety appear frequently, it tends to interfere with the normal activities in everyday life and puts an adverse impact on relationships. Homeopathic remedies for anxiety works in a mild, gentle and effective manner to gradually reduce the physical and mental reactions associated with anxiety.","•Aconitum Napellus\t•Arsenic Album\t•Argentum Nitricum\t•Gelsemium Sempervirens\t•Opium\t•Calcarea Carb\t•Phosphorus\t•Coffea Cruda\t•Ignatia Amara\t•Kali Phos\t•Lilium Tigrinum","https://www.drhomeo.com/anxiety/homeopathic-remedies-for-anxiety/"));
        exampleList.add(new symptomsClass("Asthma","Homeopathy is a safe science that offers a permanent cure for asthma and helps remove asthma from the root. These medicines set off the body’s own restorative processes, mainly strengthening its natural healing system to make it strong enough to fight the condition. In case asthma is allergic in origin, these medicines start by treating the allergies causing asthma to completely uproot the disease. They are natural, safe and free from any adverse side-effects. They can be prescribed to people of all age groups.","•Arsenic Album\t•Spongia Tosta\t•Antimonium Tartaricum\t• Ipecac\t•Sambucus Nigra","https://www.drhomeo.com/asthma/homeopathic-medicines-for-asthma/"));
        exampleList.add(new symptomsClass("Back Pain","Homeopathy is known to effect magical recovery in back pain cases whether resulting from disc complaint, arthritis, injuries or muscle strain. It offers a wide range of highly effective remedies prescribed after detailed analysis and evaluation of symptoms. They are natural and therefore, safe for consumption by all age groups.","• Rhus Tox\t•Bryonia Alba\t•Aesculus Hippocastanum\t•Kali Carb\t•Guaiacum Officinale\t•Cimicifuga Racemosa","https://www.drhomeo.com/back-pain/10-best-homeopathic-medicines-for-back-pain/"));
        exampleList.add(new symptomsClass("Bleeding Gums","At certain times bleeding from gums can arise from brushing the teeth in a harsh and rough manner. Wearing ill-fitting dentures and improper flossing can also lead to bleeding from gums. But bleeding from gums that appears frequently can be a sign of gum disease or something more serious. It is therefore important to identify the reason behind frequent bleeding from gums. Homeopathic medicines for bleeding gums help manage the swelling, pain, sensitivity, tenderness and pus discharge from the gums wherever present.","•Merc Sol\t•Kreosote \t•Hamamelis \t•Phosphorus \t•Bovista \t•Silicea \t•Hepar Sulph","https://www.drhomeo.com/homeopathic-treatment/10-homeopathic-medicines-for-bleeding-gums/"));
        exampleList.add(new symptomsClass("Body Pain","Homeopathy Remedies are very effective in treating general body pains and aches. These body pains can be general body pains caused by exertion etc or caused by more specific reason like fevers or joint inflammation. As homeopathy is a more symptom-based system of medicine ( this means that symptoms are given more preference over pathological condition while choosing the right remedy ) the medicine set remains quite same for general as well as specific reasons for causing body pains. Homeopathic medicines for body pains are a natural substitute for painkillers. The best feature while using medicine for treating body pains is that they are totally side effect free and are made from naturally occurring plants and substances.","•Rhus Toxicodendron\t•Arnica Montana\t•Gelsemium Sempervirens\t•Magnesium Phosphorica\t•Ruta Graveolens\t•Bryonia Alba\t•Eupatorium Perfoliatum\t•Arnica Montana","https://www.drhomeo.com/pain/natural-homeopathic-remedies-for-body-pains-and-aches/"));
        exampleList.add(new symptomsClass("Bone Pain","Bone Pain can be the result of various reasons. It could be due to Osteomyelitis, Osteoporosis, bone cancer, Multiple Myeloma, Pagets Disease, Sickle Cell Anemia and various fevers, including Influenza and Dengue. Bone Pains can be effectively treated by natural medicines. The medicines are given after considering the cause of the pain, the bone involved and the worsening and relieving factors in each patient. Apart from providing relief from pain in bones, These medicines also eradicate the disease process that is behind Bone Pain. Following relief from acute pain, the natural Homeopathic medicines for bone pain will work towards root extraction of the disease","•Arnica\t•Symphytum\t•Agaricus\t•Eupatorium Perfoliatum\t•Mezereum\t•Aurum Met","https://www.drhomeo.com/bone-pain/5-best-homeopathic-medicines-for-bone-pain/"));
        exampleList.add(new symptomsClass("Burns","Burns refers to the skin injury arising out of exposure to heat, chemicals and electricity. Burns can also be caused by radiations (from sun or X-rays). Burns can involve just the outer layer of skin, or can penetrate the deeper layers and in the severe cases, even up to bones and muscles.When only the outer or superficial skin is burnt, it is called first degree burns. Here, the skin gets red with pain and swelling. In second and third degree burns, the injury involves the deeper layers of skin partially or in whole thickness, respectively.In second degree burns, blisters (fluid-filled eruptions) appear along with redness and swelling of skin. In third degree burns, the skin appears white or brown. In the fourth degree burns, the skin appears black and charred, exposing the bones and muscles. The third and fourth degree burns are painless.","•Cantharis\t•Urtica Urens\t•Causticum\t•Calendula\t• Hepar Sulph\t•Calcarea Sulph\t•Arsenic Album","https://www.drhomeo.com/skin-problem/homeopathic-remedies-for-burns/"));
        exampleList.add(new symptomsClass("Breast cancer","The very word “cancer” conjures up images of impending death and chemotherapy sessions. The early stage of this dreadful disease, however, is curable with proper Homeopathic medicines that can provide holistic treatment for cancer. Cancer is characterised by the unwanted increase in body cells. In a normal healthy condition, the cells are born and destroyed at a proper time. In cancerous conditions, the division and multiplication of cells becomes uncontrollable and occurs at a very high pace. Homeopathy has a huge number of medicines, which are made of natural substances, to deal with early stage cancer cases. In advanced stages of cancer,however, Homeopathic remedies cannot provide a cure. In such cases, only palliation — care that makes you feel better though it can’t cure — is possible with natural Homeopathic medicines.It must be kept in mind though that the natural Homeopathic remedies for cancer are completely safe with no side effects.","•Conium\t•Phytolacca\t•Hydrastis \t•Asterias Rubens\t•Hydrastis","https://www.drhomeo.com/homeopathic-treatment/homeo-medicines-cancer/"));
        exampleList.add(new symptomsClass("Stomach Cancer","The effective natural Homeopathic medicines to treat stomach cancer are Arsenic Album, Phosphorus and Lycopodium. The Homeopathic medicine selection depends entirely upon the symptoms of each patient. Arsenic Album is a very beneficial Homeopathic remedy for burning type of pains in stomach of patients diagnosed with stomach cancer. Dark blood is present in vomitus and stool. The stool is also very offensive. The stool and vomiting get worse after eating or drinking anything. Extreme weakness and fear of death are present to the utmost degree. The patient requiring Arsenic Album usually craves for warm drinks. Natural Homeopathic medicine Phosphorus is the best remedy when bright red blood appears in vomitus or stool. The stool is followed by extreme weakness. The painin the stomach getting relieved by taking cold drinks is a symptom of high value to use this Homeopathic medicine. ","•Arsenic Album\t•Phosphorus \t•Lycopodium\t•Arsenic Album","https://www.drhomeo.com/homeopathic-treatment/homeo-medicines-cancer/"));
        exampleList.add(new symptomsClass("Colorectal Cancer","The top Homeopathic medicines for Colorectal Cancer are Alumina, Aloe and Nitric Acid. Alumina is the best Homeopathicremedy whenconstipation of the severest form is present in patients of Colorectal Cancer. The stool remains in the rectum for long without any urge to pass it. The passage of stool requires great straining even if the stool is soft. Homeopathic medicine Aloe is the ideal remedy when persistent diarrhoea (loose stool) is the prominent symptom in patients with Colorectal Cancer. The stool is preceded and attended with cutting pains in rectum. The pains get better after passing stool. The stool may contain blood with burning in rectum. It may also pass involuntarily. Weakness, sweating and even faintness follow the passage of stool. Homeopathic medicine Nitric Acid suits patients of Colorectal Cancer who have bright red bleeding from rectum during stool. This is associated with violent pain in rectum that continues for many hours after passing stool.","•Colorectal Cancer\t•Alumina\t•Aloe \t•Nitric Acid","https://www.drhomeo.com/homeopathic-treatment/homeo-medicines-cancer/"));
        exampleList.add(new symptomsClass("Lungs Cancer","Acalypha Indica, Bryonia Alba and Phosphorus are the top natural Homeopathic medicines for treatment of lung cancer. Acalypha Indica is the top Homeopathic remedyfor lung cancer patients when the blood from lungs is bright red and usually worse in morning. This is accompanied by hard and dry cough. The patients who can benefit byHomeopathic medicine Acalypha Indica are emaciated, which increases gradually. Bryonia Alba is the top Homeopathic medicine when rust-coloured sputa is spit out with dry cough. Pain in chest on coughing is usually present, mainly of stitching character. Phosphorus is the Homeopathic medicine that is recommended for chest heaviness and oppression. This can be accompanied by burning in the chest. The sputa is bright red in colour. The patient may show an excessive desire for cold drinks along with chest symptoms.","•Acalypha Indica\t•Bryonia Alba\t•Phosphorus \t•Acalypha Indica","https://www.drhomeo.com/homeopathic-treatment/homeo-medicines-cancer/"));
        exampleList.add(new symptomsClass("Colds","Once you get a cold, the instant human reaction is to somehow get rid of it as soon as possible. Allopathic medicines over the counter may provide you with some relief from a runny or stuffy nose, sneezing, headache and body ache for a short duration, but the viral infection far from leaves your body. The cold, or the viral infection of the upper respiratory tract, recurs and that can be even more frustrating. Here is where Homeopathic remedies can of great help. Homeopathic remedies for colds go to the crux of the problem and ensure that the viral infection is rooted out of the body. They can cure it effectively and has no side effects as these are made from natural substances and hence, are completely safe, whereas homeopathic remedies to prevent colds can ensure that there is no recurrence.","•Arsenic Album\t•Aconite\t•Gelsemium\t•Nux Vomica\t•Belladonna","https://www.drhomeo.com/common-cold/warm-up-to-homeopathic-remedies-for-cold/"));
        exampleList.add(new symptomsClass("Cough","Homeopathic treatment for cough is highly effective in most cases. Homeopathy uses medicines of natural origin for treating cough and they are, therefore, safe to use for persons of all age group. These medicines work to treat the cause of the cough so as to bring about a complete recovery in a natural way.","•Antimonium Tart\t•Ipecac\t• Drosera Rotundfolia\t•Conium Maculatum\t•Spongia Tosta\t•Corallium Rubrum\t•Millifolium\t•Natrum Mur","https://www.drhomeo.com/cough/homeopathic-remedies-for-cough/"));
        exampleList.add(new symptomsClass("Ear Pain","Ear pain or an earache that persists needs medical intervention. Earache, or Otalgia in medical terms, usually occurs because of two reasons. The first is a local cause due to a problem within the ear. The local cause is mainly an infection of the middle ear (Otitis Media). The second reason is the referred cause or pain that does not start in the ear itself but is referred secondarily to the ear through some primary problem in another part of the body.  Here, the primary problem can be in the teeth (dental caries, cutting the wisdom tooth) or throat infection (Tonsillitis) and the pain through them extends to the ear.","•Belladona\t•Chamomilla\t•Verbascum Thapsus\t•Pulsatilla\t•Hepar Sulph\t•Psorinum\t•Belladonna","https://www.drhomeo.com/homeopathic-treatment/homeopathic-medicines-ear-pain/"));
        exampleList.add(new symptomsClass("Elbow Pain","Elbow pain is a surprisingly common problem that affects the elbow joint. The most common cause of elbow pain is an injury. The nature of elbow pain varies from person to person and majorly depends on the cause; it can be sharp, dull, burning, tearing or shooting in nature. It may be constant or intermittent depending on the cause of the pain. Elbow pain while bending and straightening, elbow pain while gripping, elbow pain when lifting are common symptoms of an injury to the elbow. Homeopathic medicine for elbow pain works by stimulating the body’s natural restorative processes for a speedy recovery.","•Rhus Tox\t•Ruta Graveolens\t•Bryonia Alba\t•Colchicum Autumnale\t• Argentum Met","https://www.drhomeo.com/homeopathic-treatment/homeopathic-medicine-for-elbow-pain/"));
        exampleList.add(new symptomsClass("Foot Pain","Homeopathic medicines recommended for foot pain are Rhus Tox, Colchicum and Aranea Diadema. Rhus Tox is best indicated where repeated stress and strain leads to pain in the foot. Colchicum is a wonderful medicine for gouty pain in the foot, while in case of pain due to bone spurs, Aranea Diadema works as one of the best Homeopathic medicines for foot pain.","•Aranea Diadema\t•Ammonium Mur\t•Calcarea Fluor\t•Rhus Tox\t•Ruta\t•Benzoic Acid","https://www.drhomeo.com/homeopathic-treatment/homeopathic-medicines-for-foot-pain/"));
        exampleList.add(new symptomsClass("Flu","Does influenza or the so-called viral fever (flu) need to be taken seriously? Can it be fatal? Is homeopathy treatment effective in preventing and controlling these viral onslaughts? The answers to all these questions is “yes”.  Because influenza virus constantly changes itself, and because only a few changes can make a non-harmful virus highly lethal, Influenzas should be taken seriously","•Rhus Toxicodendron\t•Nux Vomica\t•Allium Cepa\t•Sabadilla\t•Arsenic Album\t•Pulsatilla\t•Ammonium Carbonicum","https://www.drhomeo.com/viral-fever/influenzas-and-homeopathy/"));
        exampleList.add(new symptomsClass("Gout","Gout is an inflammatory joint disease that arises due to an increase in levels of the uric acid in the blood. Any joints in the body can be affected with gout, although the joint at the base of the great toe has a higher chance of developing the condition. Increased uric acid is not a disease and by itself is not dangerous. However, if excess uric acid levels lead to formation of crystals between the joints, gout can develop. In some individuals excess levels also lead to the formation of kidney stones.","•Bryonia Alba\\t•Benzoicum Acidum\\t• Colchicum Autumnale \\t•Lycopodium Clavatum\\t•Ledum Pal\\t•Abrotanum\\t•Causticum\\t•Berberis Vulgaris","https://www.drhomeo.com/gout/homeopathic-medicine-gout/"));
        exampleList.add(new symptomsClass("Joint Pain","In the age of diagnosis where every illness gets slotted into a diagnosis, some set of symptoms just go undiagnosed. Most of the pains in joints have some diagnosis or the other, but quite a few tend to go undiagnosed. This is where homeopathy has a big role to play; homeopathic remedies for joint pains work on a symptom-based system of medicine and the prescription does not get affected by the scientific diagnosis. In this article, I am trying to cover all aspects of joint pains according to their symptoms and their indicated remedies.","•Rhus Tox\t•Causticum\t•Arnica\t•Actea Spicata\t•Chinum Sulph\t•Pulsatilla\t•Colchicum","https://www.drhomeo.com/joint/top-ten-homeopathic-remedies-for-joint-pains/"));
        exampleList.add(new symptomsClass("Knee Pain","Knee pain can be treated wonderfully well with medicines, which are natural and therefore, safe for use. Natural medicines are helpful in both acute and chronic knee pain. They are safe for use among all age groups, without any risk of toxicity. They help in relieving the pain in the knee and the accompanying symptoms such as swelling, tenderness and stiffness.","•Calcarea Carb\t•Ruta\t•Causticum\t•Calcarea Carb\t•Bryonia\t• Salicylic Acid\t•Symphytum","https://www.drhomeo.com/knee/top-homeopathic-medicines-knee-pain/"));
        exampleList.add(new symptomsClass("Muscle pain","Applying an ointment or spraying a pain reliever is the general tendency of almost everyone suffering from muscle pain. But these provide just temporary relief and the real cause of muscle pain is not addressed. Here’s where Homeopathy can be of real help. The natural Homeopathic remedies for muscle pain not only provide relief, but also strike at the root of the problem and cure muscle pain effectively. They are also completely safe with no side effects.","•Ferrum Metallicum\t•Nux Moschata\t•Actaea Racemosa\t•• Gelsemium Sempervirens\t•Ranunculus Bulbosus","https://www.drhomeo.com/pain/natural-homeopathic-remedies-for-muscle-pain-and-aches/"));
        exampleList.add(new symptomsClass("Nerve Pain","Nerve pain can feel like an electric shock, or like a pinprick or even a burning sensation. Nerve pain is a symptom of various medical conditions. It can disturb and alter your life. The countless nerves are the body’s messaging system — conveying sensations like a pain to the brain. In the case of nerve pain, the messaging system gets disturbed because of damage to the nerve from a physical injury or a disease. It is thus not easy to recognise the cause of the nerve pain. The Homeopathic medicines for nerve pain are of great help in providing relief to the patient without any side effects as these are made of natural substances. These natural remedies are given after carefully noting down the symptoms, identifying the reasons for nerve pain and extricating from the root the underlying causes of nerve pain.","•Magnesium Phos\t• Hypericum\t•Kalmia\t•Aconitum Napellus\t•Belladonna\t•Chamomilla","https://www.drhomeo.com/homeopathic-treatment/homeopathic-medicines-nerve-pain/"));
        exampleList.add(new symptomsClass("Shoulder Pain","The human shoulder is made up of a shoulder joint and different muscles, tendons and ligaments. It is one of the largest joints of the body that accommodates a wide range of movements. This complex joint is highly movable but is also one of the most unstable joints in the body. Any pain arising in the shoulder joint or the surrounding muscles, ligaments, and tendons is called shoulder pain. Homeopathic medicines for shoulder pain provide relief by stimulating the body’s natural healing process.","•Sanguinaria Can\t•Ferrum Met\t•Colchicum Autumnale\t• Phytolacca Decandra\t•Rhus Tox\t•Bryonia Alba\t•Ruta Graveolens","https://www.drhomeo.com/homeopathic-treatment/homeopathic-medicines-shoulder-pain/"));
        exampleList.add(new symptomsClass("Skin Dry","Dry skin can lead to itching, scratching, bleeding, parched lips, cracked skin and even wrinkles, but worse than all these symptoms, it can really affect the psyche of a person, making him or her very self-conscious about the physical appearance and lowering the confidence levels as a result. The intensity of skin dryness can vary from mild dryness to severe dryness with cracks. Bleeding may also occur from cracks and in a few persons, dry skin can be accompanied by wrinkling of the skin.","•Petroleum\t•Sulphur\t•Bryonia\t•Sarsaparilla\t•Malandrium","https://www.drhomeo.com/skin/homeopathic-remedies-for-dry-skin/"));

    }


    private void setUpRecyclerView() {
        RecyclerView recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setHasFixedSize(true);
        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(this);
        adapter = new adapterClass(exampleList);

        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setAdapter(adapter);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater =getMenuInflater();
        inflater.inflate(R.menu.menu_item,menu);

        MenuItem menuItem =  menu.findItem(R.id.search_Action);
        SearchView searchView = (SearchView) menuItem.getActionView();
        searchView.setImeOptions(EditorInfo.IME_ACTION_DONE);
        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String s) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String s) {
                adapter.getFilter().filter(s.toString());
                return false;
            }
        });
        return super.onCreateOptionsMenu(menu);
    }

    }
